const tableNames = {
  BriefStatement: 'Brief Statement',
  Expertise: 'Expertise',
  Languages: 'Languages',
  Resume: 'Resume',
  EduEmployee: 'Edu_Employee',
  Profile: 'Profile',
  EducationalDetails: 'Educational Details',
  Certifications: 'Certifications',
  ProjectsWorks: 'Work Samples',
  EmploymentHistory: 'Employment History',
  JobSearch: 'Job Search',
  EmpVideo: 'Employee Videos',
  EmployeeUpcomingInterview:'Employee Upcoming Interviews',
  EmployeeAppliedJobs:'Applied Jobs',
  EmployeeAppliedJob:'Apply Job',
  EmployeeFavouriteJobs:'Favourite Jobs',
  EmployeeFavouriteJob:'Favourite Job',
  EmployeeHostDevelopment:'Host Professional Development',
  EmployeeUpcomingDevelopment:'Upcoming Professional Development',
  EmployeeRegisteredDevelopment:'Registered Development',
  EmployeeCustomMessage:"Custom Messages",
  SubmitRequest:"Submit Request",
  RegisterDevelopment:"Register Development",
  ReviewResume:"Review Resume",
  MediaLibrary:"Media",
  JobView:"Job View",
  CustomMessageSendVideo: "Send Video",
  CustomMessageSendQuestion:"Review Custom Questions",
  CustomeMessageFilter: "Custom Messages",
  Notifications:"Notifications",
  PostJob:"Post Job",
  EmployerPostService:"Post Service",
  ReviewApplicants:"Review Applicants",
  EmployerPostServiceAppliant:"Review Service Provider Applicants",
  EmployerSubmitPostService:"Submit Service",
  ViewDevelopmentDetails:"View Development Details",
  ViewRegisteredDevelopmentDetails:"View Registered Development Details",
  Document:'Document',
  Service_ProviderUpcomingInterviews:"Service_Provider Upcoming Interviews",
  ViewInterviewServiceProvider:"View Interview Service Provider",
  ServiceSearch:"Service Search",
  ServiceView:"Service View",
  AppliedServices:"Applied Services",
  ViewAppliedService:"View Applied Service",
  FavouriteServices:"Favourite Services",
  FavouriteService:"Favourite Service",
  ViewFavouriteService:"View Favourite Service",
  ApplyService:"Apply Service",
  ServiceProvider:"Service_Provider",
  ScheduleInterview:"Schedule Interview",
  AddVideo:'Add Video'
};  

export { tableNames };
